# Generated by Django 3.0.8 on 2020-07-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseModel', '0002_auto_20200725_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=32)),
                ('zh', models.CharField(max_length=128)),
                ('ja', models.CharField(max_length=128)),
                ('en', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='vtuber',
            name='twitter_id',
            field=models.CharField(default='', max_length=128),
        ),
    ]
