# Generated by Django 3.0.8 on 2020-08-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseModel', '0003_auto_20200728_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='status',
            field=models.CharField(default='translating', max_length=32),
        ),
        migrations.AddField(
            model_name='translate',
            name='translated',
            field=models.BooleanField(default=False),
        ),
    ]
