# Generated by Django 3.0.8 on 2020-08-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBaseModel', '0005_auto_20200806_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voice',
            name='hot',
        ),
        migrations.RemoveField(
            model_name='voice',
            name='new',
        ),
        migrations.AddField(
            model_name='voice',
            name='tag',
            field=models.CharField(default='', max_length=32),
        ),
    ]
